import numpy as np

configfile: "config/config.yaml"

SPECIES = list()
INFOS = config['species']
for i in config['species']:
    SPECIES.append(i)


def get_code_taxon(wildcards):
    return INFOS[wildcards.specie]['code']


def get_conda(environnement):
    return "../envs/" + environnement + ".yaml"


def get_part():
    res = list()
    for i in list(range(1,10001)):
        i = str(i)
        if len(i) == 1:
            i = '0000' + i
        elif len(i) == 2:
            i = '000' + i
        elif len(i) == 3:
            i = '00' + i 
        elif len(i) == 4:
            i = '0' + i   
        res.append(i)
    return res


include: "rules/run_orthomcl.smk"

rule all:
    input:
        orthologs = "results/OrthoMCL/pairs/potentialOrthologs.txt",
        inparalogs = "results/OrthoMCL/pairs/potentialInparalogs.txt",
        coorthologs = "results/OrthoMCL/pairs/potentialCoorthologs.txt"




